### ISSUE TITLE
Issue with adding a specific `I18NProvider` implementation

### ISSUE THREAD

**Issue by nikbucher** [vaadin/base-starter-flow-quarkus#133]
Hi,

I tried to add my specific `I18NProvider` implementation, but it doesn't work as expected. Even defining the I18n Provider Property doesn't help, even worse, a ClassNotFoundException is thrown.

![Screenshot 2024-02-29 at 16 26 54](https://github.com/vaadin/base-starter-flow-quarkus/assets/1334238/566feee2-9809-420e-9954-d598ded14722)

I've provided a sample here https://github.com/nikbucher/base-starter-flow-quarkus/tree/v24-i18n.

Interestingly, I discovered that when I inject the `I18NProvider` in e.g. the `GreetService` or the `MainView` then it works correctly, even I don't use the injected `I18nProvider`.

Do I miss something? Thanks in advance.

Best regards - Nik

**Comment by mcollovati** [comment]
Vaadin Quarkus add-on is doing a programmatic lookup.
You have to mark your implementation as `@Unremovable`, otherwise Quarkus will remove the bean because it considers it unused.

**Comment by mcollovati** [comment]
Here's a link to a related issue https://github.com/vaadin/quarkus/issues/147

**Comment by nikbucher** [comment]
Thanks a lot! It works now as expected

**Comment by nikbucher** [comment]
Thanks a lot! It works now as expected
