### ISSUE TITLE
OIDC Authentication 

### ISSUE THREAD

**Issue by AbdullahGheith** [vaadin/base-starter-flow-quarkus#40]
Doesn't seem to be working.

How to reproduce:

- Start keycloak server
- add this to application.properties

```
quarkus.oidc.auth-server-url=http://localhost:8443/auth
quarkus.oidc.client-id=x
quarkus.oidc.credentials.secret=x
quarkus.oidc.application-type=web_app
```

This byitself should work (by work, i mean it should redirect to keycloak auth flow), but it doesnt unless you add: 

```
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

Now it redirects to keycloak auth flow.

Then i inject my identity: public testPage(SecurityIdentity identity)
And i can say getPrincipal().getName() and it shows me admin correctly.

but the problem is that roles are empty.
I look in my token, theres no roles. fair enough. i go to my client page and add a mapping for client roles.

Now i cant access my page at all, even though @PermitAll is on my class

**Comment by klenkes74** [comment]
I needed to add a few more configurations in my application.properties:

```
quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.roles.source=userinfo
quarkus.oidc.roles.role-claim-path=realm_access/roles
```

I enforce the roles on quarkus application.properties side (quarkus.http.auth.permission.* and quarkus.http.auth.policy.*) but it works ...

**Comment by czp13** [comment]
Is this happening still to you @AbdullahGheith? Could you try out pls idea mentioned above?

**Comment by AbdullahGheith** [comment]
Unfortunately, i switched to Spring boot, and that just worked..

**Comment by czp13** [comment]
Thank you very much for the lightning-fast reply @AbdullahGheith! I am glad to hear it is working with Spring Boot. 
I guess we can just close this one soonish as no other user had this or a similar problem in the past year, and you also moved on. Plus the above properties could have worked. Take care.

**Comment by czp13** [comment]
As we discussed in our flow meeting, we can close this one:
- as the suggested solution may work,
- no other users seemingly affected by this one,
- @AbdullahGheith also does not experience this anymore (switched to Spring Boot),

Thanks @AbdullahGheith once more, take care.
