### ISSUE TITLE
Task vaadinBuildFrontend fails on Gitlab Pipeline with dependency error

### ISSUE THREAD

**Issue by Dharmik2510** [vaadin/base-starter-flow-quarkus#76]
**Project working fine in my Local VM, However, in GitLab pipeline I am getting this error.**

**Using vaadin: 23.3.5**

Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
using '/root/.vaadin/node/node /root/.vaadin/node/lib/node_modules/npm/bin/npm-cli.js --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
Command `/root/.vaadin/node/node /root/.vaadin/node/lib/node_modules/npm/bin/npm-cli.js --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install` failed:
>>> Dependency ERROR. Check that all required dependencies are deployed in npm repositories.
> Task :vaadinBuildFrontend FAILED
:vaadinBuildFrontend (Thread[Execution worker for ':',5,main]) completed. Took 1 mins 16.641 secs.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Npm install has exited with non zero status. Some dependencies are not installed. Check npm command output
* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by mshabarov** [comment]
@Dharmik2510 thank you for the issue! Can you please provide more information: the exact stack trace from the logs that highlights what was the problem (e.g. TS compilation error because of version mismatch) and also the Node.js and npm version used?

**Comment by mshabarov** [comment]
Could you also please try with the latest Vaadin 23.3.10 version (not released yet, but should be available in the maven central soon). We had a fix for TS compiler in some intermediate version between 5 and 10.

**Comment by czp13** [comment]
Sorry, but until you could provide a bit more context (npm, node versions, exact/full stacktrace,..), there is nothing that we can do. Until that, we consider this an issue specific to your application or environment. Please reopen the issue if you discover a root cause not dependent on your application or environment and can provide the information we asked for reproducing the issue. Thank you.
